### ISSUE TITLE
Marquee box with mouse that spawns blocks

### ISSUE THREAD

**Issue by resindrake** [resindrake/townplanner#1]
* [x] A rectangular marquee box should appear when you click and hold
* [x] Left-clicking should draw hollow rectangles with walls behind them
* [x] Shift-left-clicking should draw hollow rectangles with walls behind them
* [x] Right-clicking should draw a marquee that draws a deletion blueprint
* [x] Shift-right-clicking should draw a marquee that clears build/delete blueprints
* moved to #12
	* ~~Pressing a key (e.g. space) should turn all blueprints onscreen into blocks (dev feature)~~
	* ~~Some way to choose which block gets drawn?~~

**Comment by resindrake** [comment]
So far, @Krutonium has managed to 'draw' a marquee when you click and drag with the mouse, but is having troubles making it then place wood blocks in another tileset. We need to figure out how to spawn wood tiles in the world when the mouse is released.

**Comment by SuscipiamSingularitatem** [comment]
ez

![2020-11-09 04-06-23](https://user-images.githubusercontent.com/26754065/98474607-1fffab80-2241-11eb-95ad-c1d1023715fe.gif)

**Comment by resindrake** [comment]
Now we want:
* the marquee to draw blueprints rather than blocks
* pressing a key (e.g. space) should turn all blueprints onscreen into blocks
* right-clicking should draw a marquee that removes blueprints

**Comment by SuscipiamSingularitatem** [comment]
As of c632404f2:
![temp](https://user-images.githubusercontent.com/26754065/98488198-7d145500-2273-11eb-8f11-f28aef100e15.gif)
