### ISSUE TITLE
Add bees

### ISSUE THREAD

**Issue by SuscipiamSingularitatem** [resindrake/townplanner#31]
Aristaeus' Law states that everything can be improved with the introduction of bees.
![](https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/58/Bee.gif)

**Comment by resindrake** [comment]
Creeping scope, should be dealt with later

**Comment by SuscipiamSingularitatem** [comment]
No, this is creeping scope:
![](https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Creeper_JE2_BE1.png)
